"""
Bridge between the MAKE image subsystem (NumPy-only) and the existing
MAKE model registry (also PyTorch-agnostic at the JSON layer).

Registers:
  - The model `make-image-research-v0` in the registry
  - Each training run with its config and dataset info
  - Each checkpoint (real .npz file with SHA-256 verification)

Updates model status to `checkpoint_available` after a successful
training run and to `inference_ready` after sampling has been verified.
"""

from __future__ import annotations

import os
from dataclasses import asdict
from typing import Any, Dict, Optional

from app.make_model.utils import sha256_file, now_iso, get_logger
from app.make_model.registry import (
    MakeModelRegistry, ModelVersion, CheckpointRecord, OWNER,
)
from app.make_model.state import ModelState


logger = get_logger("make_model.image.registry_bridge")


class ImageRegistryBridge:
    IMAGE_MODEL_NAME = "make-image-research-v0"
    ARCH_VERSION = "make-image-cpu-unet-v1"
    SCHEMA_VERSION = 1

    def __init__(self, registry: Optional[MakeModelRegistry] = None):
        self.registry = registry

    def _reg(self) -> MakeModelRegistry:
        if self.registry is None:
            from app.make_model.registry import get_registry
            self.registry = get_registry()
        return self.registry

    def register_model(self, parameter_count: int, config: Dict[str, Any]) -> Dict[str, Any]:
        reg = self._reg()
        mv = ModelVersion(
            name=self.IMAGE_MODEL_NAME,
            arch_version=self.ARCH_VERSION,
            created_at=now_iso(),
            description=(
                "MAKE proprietary CPU-only NumPy image denoiser. "
                f"arch={self.ARCH_VERSION}, params~{parameter_count}."
            ),
            config=config,
            parameter_count_estimate=int(parameter_count),
            status=ModelState.ARCHITECTURE_DEFINED.value,
            notes="Generated by make.image subsystem on CPU (no PyTorch).",
        )
        reg.register_model(mv)
        return mv.to_dict()

    def register_training_run(self, run_id: str, config: Dict[str, Any],
                              dataset_info: Dict[str, Any],
                              steps_planned: int) -> Dict[str, Any]:
        reg = self._reg()
        run = {
            "id": run_id,
            "kind": "image",
            "model_name": self.IMAGE_MODEL_NAME,
            "arch_version": self.ARCH_VERSION,
            "created_at": now_iso(),
            "config": config,
            "dataset_info": dataset_info,
            "steps_planned": steps_planned,
            "status": "running",
        }
        reg.register_training_run(run)
        # Update dataset_prepared since we have a manifest
        try:
            reg.update_model_status(self.IMAGE_MODEL_NAME, ModelState.DATASET_PREPARED.value,
                                    notes=f"Dataset manifest={dataset_info.get('sha256_manifest', '')}")
        except Exception:
            pass
        return run

    def finalize_training_run(self, run_id: str, steps_done: int,
                              final_loss: float, checkpoint_path: str) -> Dict[str, Any]:
        reg = self._reg()
        reg.update_training_run(run_id, {
            "status": "completed",
            "steps_done": steps_done,
            "final_loss": final_loss,
            "checkpoint_path": checkpoint_path,
            "completed_at": now_iso(),
        })
        try:
            reg.update_model_status(self.IMAGE_MODEL_NAME, ModelState.CHECKPOINT_AVAILABLE.value,
                                    notes=f"Checkpoint at {checkpoint_path}")
        except Exception:
            pass
        return reg.get_training_run(run_id) or {}

    def register_checkpoint(self, checkpoint_path: str, training_run_id: str,
                            config: Dict[str, Any], dataset_info: Dict[str, Any],
                            global_step: int, epoch: int = 0,
                            metric_summary: Optional[Dict[str, Any]] = None,
                            notes: str = "") -> Dict[str, Any]:
        reg = self._reg()
        if not os.path.exists(checkpoint_path):
            raise FileNotFoundError(checkpoint_path)
        sha = sha256_file(checkpoint_path)
        cp_id = f"{self.IMAGE_MODEL_NAME}-step{global_step}-{sha[:8]}"
        rec = CheckpointRecord(
            id=cp_id,
            model_name=self.IMAGE_MODEL_NAME,
            model_version=self.IMAGE_MODEL_NAME,
            arch_version=self.ARCH_VERSION,
            owner=OWNER,
            created_at=now_iso(),
            path=checkpoint_path,
            sha256=sha,
            bytes=os.path.getsize(checkpoint_path),
            training_run_id=training_run_id,
            global_step=int(global_step),
            epoch=int(epoch),
            config=config,
            dataset_name=str(dataset_info.get("name", "")),
            dataset_manifest_sha=str(dataset_info.get("sha256_manifest", "")),
            git_commit="n/a",
            framework_version="numpy",
            pytorch_version="none",
            metric_summary=metric_summary or {},
            notes=notes,
        )
        reg.register_checkpoint(rec)
        return rec.to_dict()

    def mark_inference_ready(self, sample_path: str, sample_sha256: str) -> Dict[str, Any]:
        reg = self._reg()
        reg.update_model_status(self.IMAGE_MODEL_NAME, ModelState.INFERENCE_READY.value,
                                notes=f"Sample verified at {sample_path} (sha256={sample_sha256[:12]})")
        return reg.get_model(self.IMAGE_MODEL_NAME) or {}